#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap          10
bspc config top_padding        -10
bspc config bottom_padding     -10

bspc config normal_border_color	"#292929"
bspc config focused_border_color	"#292929"
bspc config presel_feedback_color	"#B68C2F"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a Pick-colour-picker state=floating
bspc rule -a Zathura state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Anki state=floating
bspc rule -a Alacritty rectangle=670x400+570+170

# Polybar
"$HOME/.config/polybar/scripts/launch.sh" &

# Cursor
xsetroot -cursor_name left_ptr &

# Android Studio Bug Fix
#wmname LG3D &
#bspc rule -a android-studio state=floating border=off follow=on &
