#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap          12
bspc config bottom_padding      -4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^1' follow=on
bspc rule -a Pick-colour-picker state=floating
bspc rule -a Zathura state=floating
bspc rule -a Lxappearance state=floating

# My conf
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
